const ENGLISH_PHRASES: ReadonlyArray<readonly [string, string]> = [
  ['EEGSleepUpper 参数与控制', 'EEGSleepUpper Parameters and Controls'],
  ['EEGSleepUpper 调试波形', 'EEGSleepUpper Debug Waveforms'],
  ['调试 EEG 显示滤波', 'Debug EEG Display Filter'],
  ['调试 Alpha 音量模式', 'Debug Alpha Volume Mode'],
  ['调试音频输出设备', 'Debug Audio Output Device'],
  ['调试 EEG 量程', 'Debug EEG Scale'],
  ['调试信号类别', 'Debug Signal Type'],
  ['标记并测试 3 次', 'Mark and Test 3 Blinks'],
  ['标记并测试 5 次', 'Mark and Test 5 Blinks'],
  ['标记 10 秒无指令', 'Mark 10 s No-command Control'],
  ['3 秒安静 + 10 秒连续眨眼', '3 s Quiet + 10 s Continuous Blinking'],
  ['闭眼 Alpha 基线', 'Eyes-closed Alpha Baseline'],
  ['音频输出设备', 'Audio Output Device'],
  ['频谱特征分', 'Spectral Feature Score'],
  ['Alpha 占比', 'Alpha Share'],
  ['Alpha 强度', 'Alpha Strength'],
  ['开启阈值', 'On Threshold'],
  ['关闭阈值', 'Off Threshold'],
  ['音量阶梯', 'Volume Steps'],
  ['4 路 EEG', '4 EEG'],
  ['6 路 PPG', '6 PPG'],
  ['等待 PC 眨眼算法服务', 'Waiting for the PC blink algorithm service'],
  ['波形', 'Waveform'],
  ['需先完成 3 秒安静 + 10 秒眨眼测量', 'Complete the 3 s quiet + 10 s blink calibration first'],
  ['睁眼基线校准', 'Eyes-open Baseline Calibration'],
  ['闭眼基线校准', 'Eyes-closed Baseline Calibration'],
  ['先测睁眼基线', 'Calibrate the eyes-open baseline first'],
  ['眨眼测量', 'Blink Calibration'],
  ['打开音乐库', 'Open Music Library'],
  ['演示曲目', 'Demo Tracks'],
  ['星河 Alpha', 'Stellar Alpha'],
  ['海岸慢潮', 'Coastal Slow Tide'],
  ['林间晨息', 'Forest Morning Breath'],
  ['雨幕白噪', 'Rain Curtain White Noise'],
  ['晨光呼吸', 'Dawn Breathing'],
  ['在线模式沿用旧自制版 Alpha 算法：音乐开启阈值由当前 Alpha 相对睁眼基线自适应计算。困意值可在 0.2.5 对照与可穿戴特征试验间切换；试验模式使用四通道中位参考、Theta 模板匹配伪迹抑制、60 秒清醒基线、质量门控和跨窗口频带比值，并与 PC 睡眠概率融合。清醒证据稳定时显示压缩在 0–19，连续困倦证据出现后恢复 20–100 的动态范围。', 'Online mode uses the validated Alpha algorithm: the music trigger adapts to current Alpha relative to the eyes-open baseline. Drowsiness can switch between the 0.2.5 reference and wearable-feature trial. The trial uses four-channel median referencing, Theta template-matched artifact suppression, a 60 s awake baseline, quality gating, cross-window band ratios, and PC sleep-probability fusion. Stable awake evidence is compressed to 0–19; sustained drowsiness evidence restores the 20–100 dynamic range.'],
  ['仅采集、显示、记录与人工标记；音乐、基线、分期和眨眼控制均已停用', 'Acquisition, display, recording and manual markers only; music, calibration, staging and blink control are disabled'],
  ['仅保留采集、记录、人工标记和基础频带显示', 'Keep acquisition, recording, manual markers and basic band displays only'],
  ['音乐、基线、分期与眨眼控制均不会运行。', 'Music, calibration, staging and blink control are disabled.'],
  ['实时切换可视时间锚点，不改变采集、保存或算法输入。', 'Changes only the visual time anchor; acquisition, recording and algorithm inputs are unchanged.'],
  ['在线模式沿用旧自制版 Alpha 算法：音乐开启阈值由当前 Alpha 相对睁眼基线自适应计算。', 'Online mode uses the validated Alpha algorithm: the music trigger adapts to current Alpha relative to the eyes-open baseline.'],
  ['试验模式先采集 60 秒高质量清醒基线，再融合频带比值与 PC 睡眠概率；低质量窗口保持上一结果。', 'Trial mode first collects a 60 s high-quality awake baseline, then fuses band ratios with PC sleep probability; low-quality windows hold the previous result.'],
  ['仅作用于“全部波形”显示。卡尔曼用于抑制逐点随机抖动：Q 越大跟随越快，R 越大越平滑但响应更慢。', 'Applies only to the All Waveforms display. Kalman filtering suppresses sample noise: larger Q tracks faster; larger R is smoother but slower.'],
  ['仅作用于脑电/纯波形模式顶部的原始 EEG；下方各频带始终按各自范围滤波。关闭后显示已正确转为有符号的原始 EEG。', 'Applies only to the raw EEG at the top of EEG/Pure Waveform modes. Band rows always use their own filters. When disabled, signed raw EEG is displayed.'],
  ['先 3 秒睁眼安静不眨眼，再每 0.5-1 秒自然眨眼一次，保持头部和下颌静止', 'Keep eyes open and still for 3 s, then blink naturally every 0.5-1 s while keeping the head and jaw still'],
  ['点击后先安静 3 秒，再连续自然眨眼 10 秒；完成后安静 5 秒检查漂移', 'After clicking, remain still for 3 s, blink naturally for 10 s, then remain still for 5 s for drift validation'],
  ['基线漂移超限，眨眼控制已暂停；稳定安静信号自动恢复中', 'Baseline drift exceeded the limit; blink control is paused and will recover automatically from stable quiet data'],
  ['数据采集模式：音乐引导与全部实时算法已关闭', 'Acquisition mode: music guidance and all real-time algorithms are disabled'],
  ['助眠已开始：可自然闭眼，系统将冻结睁眼基线并等待 Alpha 触发音乐', 'Sleep guidance started: close your eyes naturally; the eyes-open baseline is frozen while the system waits for the Alpha trigger'],
  ['请完成基线测量并选择音乐，然后点击开始助眠', 'Complete calibration, select music, then click Start Sleep Guidance'],
  ['请先完成 3 秒安静 + 10 秒眨眼测量', 'Complete the 3 s quiet + 10 s blink calibration first'],
  ['阶段 1/2：睁眼安静、头部不动、不要眨眼（3 秒）', 'Stage 1/2: eyes open, head still, do not blink (3 s)'],
  ['阶段 2/2：每 0.5–1 秒自然眨眼一次（10 秒）', 'Stage 2/2: blink naturally every 0.5–1 s (10 s)'],
  ['自然闭眼，保持清醒和静止，不要咬牙或转头', 'Close your eyes naturally, remain awake and still, and do not clench your jaw or turn your head'],
  ['平视前方，面部放松，尽量少眨眼，保持头部不动', 'Look forward, relax your face, minimize blinking and keep your head still'],
  ['保持睁眼安静，前 3 秒不要眨眼', 'Keep eyes open and still; do not blink for the first 3 s'],
  ['连续自然眨眼，每 0.5–1 秒一次；保持头和下颌不动', 'Blink naturally every 0.5–1 s; keep the head and jaw still'],
  ['用于与 PSG 对齐：接下来10秒持续、均匀连续眨眼，倒计时结束后停止', 'For PSG alignment: blink continuously and evenly for the next 10 s, then stop when the countdown ends'],
  ['匿名受试者 ID 仅可使用 1–32 位字母、数字、点、下划线或连字符', 'Anonymous participant ID may contain 1–32 letters, digits, periods, underscores or hyphens'],
  ['实时处理过载，已清理', 'Real-time display overload; cleared'],
  ['个过期显示样本；记录文件不受影响', 'stale display samples; recording files are unaffected'],
  ['正在持续扫描 BLE 设备，连接成功后自动停止', 'Continuously scanning BLE devices; scanning stops after connection'],
  ['尚未发现 TD 头戴设备，正在继续扫描', 'No TD headset found yet; scanning continues'],
  ['设备已连接，无需扫描', 'Device is already connected; scanning is unnecessary'],
  ['扫描将继续', 'scanning continues'],
  ['正在设置采样率', 'setting sample rate'],
  ['采样率已设置为', 'Sample rate set to'],
  ['正在向 FFF5 写入', 'Writing to FFF5:'],
  ['采样率设置失败', 'Sample-rate command failed'],
  ['正在自动重连设备', 'Automatically reconnecting device'],
  ['自动重连失败', 'Automatic reconnection failed'],
  ['正在创建数据与标记文件', 'Creating data and marker files'],
  ['正在写入并关闭记录文件', 'Writing and closing recording files'],
  ['记录已停止，数据与标记文件已保存', 'Recording stopped; data and marker files saved'],
  ['记录中：点击按钮即可写入同步标记', 'Recording: click a button to write a synchronized marker'],
  ['正在创建独立电压记录文件', 'Creating independent voltage log'],
  ['电压记录已停止并保存', 'Voltage recording stopped and saved'],
  ['整夜防睡眠配置失败', 'Overnight sleep-prevention setup failed'],
  ['读取整夜防睡眠状态失败', 'Failed to read sleep-prevention status'],
  ['请先开始记录，再添加眨眼或伪迹标记', 'Start recording before adding blink or artifact markers'],
  ['请先开始记录，再添加标记', 'Start recording before adding markers'],
  ['请先开始记录，再启动眨眼真值测试', 'Start recording before running a blink ground-truth trial'],
  ['请先从音乐库选择一首助眠音乐', 'Select a sleep track from the music library first'],
  ['请先在后台设置中启用音乐引导', 'Enable sleep music guidance in Settings first'],
  ['请先完成睁眼基线测量', 'Complete the eyes-open baseline first'],
  ['请先完成睁眼基线', 'Complete the eyes-open baseline first'],
  ['睁眼平视，保持静止', 'Eyes open, look straight ahead, and remain still'],
  ['先 3 秒睁眼安静，再连续自然眨眼 10 秒', 'Keep eyes open and still for 3 s, then blink naturally and continuously for 10 s'],
  ['准备：先静止 3 秒', 'Prepare: remain still for 3 s'],
  ['请先完成闭眼基线测量', 'Complete the eyes-closed baseline first'],
  ['已启用眨眼控制，请先完成眨眼基线测量', 'Blink control is enabled; complete blink calibration first'],
  ['PC 实时算法尚未就绪，请先启动算法服务', 'The PC real-time algorithm is not ready; start the service first'],
  ['个体 Alpha 基线测量需要启用本机 PC v1.2 算法服务', 'Individual Alpha calibration requires the local PC v1.2 service'],
  ['当前 WebView 无法枚举音频输出设备，将使用系统默认输出', 'The current WebView cannot enumerate audio outputs; the system default will be used'],
  ['当前 WebView 不支持指定音频输出，音乐将使用系统默认设备', 'The current WebView cannot select an audio output; music will use the system default'],
  ['未取得音频权限。请到“系统设置 → 隐私与安全性 → 麦克风”允许 iFET EEG Client Sleep，然后重新点击“授权刷新”。', 'Audio permission is unavailable. Open System Settings > Privacy & Security > Microphone, allow iFET EEG Client Sleep, then click Authorize & Refresh again.'],
  ['自动播放被系统阻止，请点击播放按钮授权', 'Autoplay was blocked by the system; click Play to authorize it'],
  ['音乐文件无法读取，请重新选择', 'The music file cannot be read; select it again'],
  ['测试声音播放失败', 'Test sound playback failed'],
  ['切换音频输出失败', 'Failed to change audio output'],
  ['音频输出列表尚未授权，请点击“授权刷新”', 'Audio outputs are not authorized; click Authorize & Refresh'],
  ['音乐只切换输出设备；设备授权不会录制音频', 'Music only switches output devices; authorization does not record audio'],
  ['未支持设备选择时自动使用系统默认输出', 'The system default output is used when device selection is unavailable'],
  ['4 路 EEG / 6 路 PPG · Alpha、眨眼、睡眠与音乐闭环参数', '4 EEG / 6 PPG channels · Alpha, blink, sleep and closed-loop music parameters'],
  ['仅在协议调试或工程排查时使用；常规采集无需发送。', 'Use only for protocol debugging or engineering diagnostics; normal acquisition does not require commands.'],
  ['设备未连接时禁止发送。采样率命令仍使用顶部的专用采样率按钮。', 'Commands are disabled while disconnected. Use the dedicated sample-rate control at the top for sampling commands.'],
  ['四通道配对眨眼诊断', 'Four-channel paired blink diagnostics'],
  ['Alpha 实时与个体双基线', 'Real-time Alpha and individual dual baselines'],
  ['记录会话与眨眼真值测试', 'Session recording and blink ground-truth trials'],
  ['保守睡眠判定', 'Conservative sleep detection'],
  ['独立功能与音乐控制', 'Independent functions and music control'],
  ['实时动作与连接', 'Real-time actions and connection'],
  ['EEGSleepUpper 综合调试', 'EEGSleepUpper Integrated Debugging'],
  ['数据采集模式运行中', 'Acquisition mode is active'],
  ['数据采集模式界面', 'Acquisition mode workspace'],
  ['调试模式界面', 'Debug mode workspace'],
  ['纯波形监测', 'Pure Waveform Monitor'],
  ['睡眠音乐引导', 'Sleep Music Guidance'],
  ['PC 睡眠算法服务', 'PC Sleep Algorithm Service'],
  ['判定与交互参数', 'Detection and Interaction Parameters'],
  ['原始滤波（全部波形）', 'Raw Filters (All Waveforms)'],
  ['全部波形显示带通（低时延）', 'All-waveform display band-pass (low latency)'],
  ['EEG 原始波形带通（低时延）', 'Raw EEG band-pass (low latency)'],
  ['设备高级指令', 'Advanced Device Commands'],
  ['后台设置', 'Settings'],
  ['设置分类', 'Settings categories'],
  ['数据采集模式', 'Acquisition Mode'],
  ['退出采集模式', 'Exit Acquisition Mode'],
  ['脑电模式', 'EEG Mode'],
  ['调试模式', 'Debug Mode'],
  ['全部波形', 'All Waveforms'],
  ['纯波形模式', 'Pure Waveform Mode'],
  ['退出纯波形', 'Exit Pure Waveform'],
  ['演示模式（模拟数据）', 'Demo Mode (Simulated Data)'],
  ['演示模式：模拟数据流入', 'Demo mode: simulated data stream'],
  ['显示模式', 'Display Mode'],
  ['界面主题', 'Theme'],
  ['信号显示时延', 'Signal Display Delay'],
  ['显示滤波', 'Display Filter'],
  ['四通道显示滤波', 'Four-channel Display Filter'],
  ['采集 EEG 显示滤波', 'Acquisition EEG Display Filter'],
  ['显示原始', 'Show Raw'],
  ['显示 Alpha', 'Show Alpha'],
  ['显示 0.7–15 Hz（眨眼）', 'Show 0.7–15 Hz (Blink)'],
  ['显示 0.5–30 Hz', 'Show 0.5–30 Hz'],
  ['EEG 自动', 'EEG Auto'],
  ['实时频谱', 'Real-time Spectrum'],
  ['频带波形', 'Band Waveforms'],
  ['采集分析显示', 'Acquisition Analysis View'],
  ['采集分析通道', 'Acquisition Analysis Channel'],
  ['分析通道', 'Analysis Channel'],
  ['分析显示', 'Analysis View'],
  ['四通道原始 EEG', 'Four-channel Raw EEG'],
  ['采集分析与事件标记', 'Acquisition Analysis and Event Markers'],
  ['采集', 'Acquisition'],
  ['四频带 · 独立 FIR 带通', 'Four Bands · Independent FIR Band-pass'],
  ['频带分离', 'Band Separation'],
  ['频带参数', 'Band Parameters'],
  ['频带占比明细', 'Band Share Details'],
  ['脑电频带占比', 'EEG Band Share'],
  ['频带能量占比饼图', 'Band Energy Share Chart'],
  ['频带占比', 'Band Share'],
  ['中位参考 · 模板匹配 · 清醒1/f校正', 'Median reference · Template match · Awake 1/f correction'],
  ['中位参考 · 伪迹门控', 'Median reference · Artifact gating'],
  ['原始波形', 'Raw Waveform'],
  ['频带', 'Band'],
  ['时间窗', 'Time Window'],
  ['频率分辨率', 'Frequency Resolution'],
  ['峰值频率', 'Peak Frequency'],
  ['FFT窗长', 'FFT Window'],
  ['相对功率', 'Relative Power'],
  ['频率', 'Frequency'],
  ['范围', 'Range'],
  ['等待至少 128 个', 'Waiting for at least 128'],
  ['样本', 'samples'],
  ['赫兹相对功率谱', 'Hz relative power spectrum'],
  ['事件标记栏', 'Event Marker Panel'],
  ['事件标记', 'Event Marker'],
  ['采集事件日志', 'Acquisition Event Log'],
  ['算法事件日志', 'Algorithm Event Log'],
  ['匿名受试者 ID', 'Anonymous Participant ID'],
  ['例如 P001；不要填写姓名或手机号', 'e.g. P001; do not enter a name or phone number'],
  ['例如 P001', 'e.g. P001'],
  ['PSG 对齐：连续眨眼 10 秒', 'PSG Alignment: Continuous Blinks for 10 s'],
  ['连续眨眼中 · 剩余', 'Continuous blinking · Remaining'],
  ['PSG 对齐标记已完成', 'PSG alignment marker completed'],
  ['开始与结束时间均写入标记文件', 'Start and end times are written to the marker file'],
  ['保存自定义标记', 'Save Custom Marker'],
  ['自定义标记', 'Custom Marker'],
  ['等待人工标记', 'Waiting for manual markers'],
  ['等待算法事件或人工标记', 'Waiting for algorithm events or manual markers'],
  ['动作速度、真假事件、佩戴或接触状态', 'Action speed, true/false event, fit or contact state'],
  ['事件、动作、佩戴或接触状态', 'Event, action, fit or contact state'],
  ['数据文件', 'Data File'],
  ['标记文件', 'Marker File'],
  ['备注', 'Notes'],
  ['睁眼', 'Eyes Open'],
  ['闭眼', 'Eyes Closed'],
  ['自然眨眼', 'Natural Blink'],
  ['单次眨眼', 'Single Blink'],
  ['眨眼误识别', 'False Blink Detection'],
  ['眨眼漏识别', 'Missed Blink'],
  ['运动伪迹', 'Motion Artifact'],
  ['体位改变', 'Position Change'],
  ['电极调整', 'Electrode Adjustment'],
  ['清醒 KSS≤3', 'Alert KSS≤3'],
  ['困倦 KSS≥7', 'Drowsy KSS≥7'],
  ['设备控制', 'Device Controls'],
  ['选择设备', 'Select Device'],
  ['当前设备', 'Current Device'],
  ['持续扫描并连接 BLE', 'Continuously scan and connect BLE'],
  ['停止持续扫描', 'Stop continuous scan'],
  ['停止扫描', 'Stop Scan'],
  ['扫描中', 'Scanning'],
  ['扫描', 'Scan'],
  ['连接', 'Connect'],
  ['断开', 'Disconnect'],
  ['已断开连接', 'Disconnected'],
  ['已连接：', 'Connected: '],
  ['已连接 ', 'Connected '],
  ['BLE 未连接', 'BLE Disconnected'],
  ['未连接', 'Disconnected'],
  ['正在连接设备', 'Connecting device'],
  ['设备电量', 'Device Battery'],
  ['连接设备后显示电量', 'Connect a device to display battery level'],
  ['等待设备发送 0x03/0x04 电压帧', 'Waiting for device 0x03/0x04 voltage frame'],
  ['等待上报', 'Waiting for report'],
  ['正在充电 · 估算电量', 'Charging · Estimated level'],
  ['已到实测耗尽电压', 'Measured cutoff voltage reached'],
  ['电量低，请尽快充电', 'Low battery; charge soon'],
  ['估算电量 · 30秒平滑', 'Estimated level · 30 s smoothing'],
  ['充电中', 'Charging'],
  ['记录电压', 'Record Voltage'],
  ['电压记录开关', 'Voltage Recording'],
  ['独立保存设备上报的电压，不要求同时记录 EEG', 'Save device voltage independently; EEG recording is not required'],
  ['电压记录中', 'Voltage Recording'],
  ['设置采样率', 'Set Sample Rate'],
  ['BLE 采样率', 'BLE Sample Rate'],
  ['向 FFF5 写入采样率命令，当前', 'Write sample-rate command to FFF5; current'],
  ['数据记录时长', 'Recording Duration'],
  ['记录时长', 'Duration'],
  ['开始记录', 'Start Recording'],
  ['停止记录', 'Stop Recording'],
  ['记录已开始', 'Recording started'],
  ['记录已停止', 'Recording stopped'],
  ['记录操作失败', 'Recording operation failed'],
  ['开始助眠并记录', 'Start Sleep Guidance and Record'],
  ['仅眨眼验证并记录', 'Blink Validation and Record Only'],
  ['结束/停止记录', 'End / Stop Recording'],
  ['处理中…', 'Processing…'],
  ['处理中', 'Processing'],
  ['整夜保护 已开启', 'Overnight Protection On'],
  ['整夜保护 待机', 'Overnight Protection Standby'],
  ['整夜保护 Windows 专用', 'Overnight Protection: Windows Only'],
  ['Windows 防睡眠已开启', 'Windows Sleep Prevention On'],
  ['实时动作', 'Real-time Action'],
  ['锁存算法动作', 'Latched Algorithm Action'],
  ['等待下一个动作', 'Waiting for next action'],
  ['设备与算法 Flag', 'Device and Algorithm Flags'],
  ['最近设备 Flag', 'Recent Device Flags'],
  ['设备 Flag', 'Device Flag'],
  ['设备 flag', 'Device Flag'],
  ['算法动作', 'Algorithm Action'],
  ['算法状态', 'Algorithm State'],
  ['算法服务', 'Algorithm Service'],
  ['算法链路', 'Algorithm Pipeline'],
  ['已关闭', 'Disabled'],
  ['无记录', 'No records'],
  ['信号质量', 'Signal Quality'],
  ['信号质量不足', 'Poor Signal Quality'],
  ['算法通道', 'Algorithm Channels'],
  ['通道权重', 'Channel Weights'],
  ['通道切换', 'Channel Switches'],
  ['通道显示', 'Channel Display'],
  ['EEG 通道', 'EEG Channel'],
  ['EEG 量程', 'EEG Scale'],
  ['绘图处理', 'Plot Processing'],
  ['累计 ', 'Cumulative '],
  ['丢包', 'Packet Loss'],
  ['目标 ', 'Target '],
  ['实收 ', 'Received '],
  ['采样统计中', 'Collecting sample statistics'],
  ['低 Hz', 'Low Hz'],
  ['高 Hz', 'High Hz'],
  ['低频 Hz', 'Low Frequency Hz'],
  ['高频 Hz', 'High Frequency Hz'],
  ['EEG 低频', 'EEG Low Cutoff'],
  ['EEG 高频', 'EEG High Cutoff'],
  ['陷波', 'Notch'],
  ['卡尔曼滤波', 'Kalman Filter'],
  ['脑电参数', 'EEG Parameters'],
  ['FFF5 十六进制指令', 'FFF5 Hex Command'],
  ['十六进制命令', 'Hex Command'],
  ['发送', 'Send'],
  ['命令已发送', 'Command sent'],
  ['困意值算法', 'Drowsiness Algorithm'],
  ['困意值试验', 'Drowsiness Trial'],
  ['可穿戴特征试验（推荐）', 'Wearable Feature Trial (Recommended)'],
  ['0.2.5 对照算法', '0.2.5 Reference Algorithm'],
  ['困意值', 'Drowsiness'],
  ['数值越高越困', 'higher values indicate greater drowsiness'],
  ['可穿戴试验', 'Wearable Trial'],
  ['实时检测', 'Real-time Detection'],
  ['实时', 'Live'],
  ['低质量保持', 'Low-quality Hold'],
  ['可穿戴频谱', 'Wearable Spectrum'],
  ['频谱 + PC 融合', 'Spectrum + PC Fusion'],
  ['清醒基线', 'Awake Baseline'],
  ['暂用', 'using'],
  ['清醒线索', 'Awake Evidence'],
  ['入睡线索', 'Sleep-onset Evidence'],
  ['过渡期', 'Transition'],
  ['睡眠指标', 'Sleep Metrics'],
  ['SOL 入睡潜伏期', 'SOL Sleep-onset Latency'],
  ['当前窗口估计', 'Current-window Estimate'],
  ['θ/α 比值', 'Theta/Alpha Ratio'],
  ['α 相对功率', 'Alpha Relative Power'],
  ['α 相对占优', 'Alpha relatively dominant'],
  ['θ 相对功率', 'Theta Relative Power'],
  ['β 相对功率', 'Beta Relative Power'],
  ['是否出现顶尖波', 'Vertex Wave'],
  ['是否进入 N2', 'N2 Stage'],
  ['纺锤波 / K 复合波', 'Spindle / K-complex'],
  ['纺锤波', 'Spindle'],
  ['K 复合波', 'K-complex'],
  ['出现', 'Detected'],
  ['未见', 'Not Detected'],
  ['未出现', 'Not Detected'],
  ['未检出', 'Not Detected'],
  ['候选', 'Candidate'],
  ['等待分期', 'Waiting for Staging'],
  ['分期预热', 'Staging Warm-up'],
  ['实时分期', 'Real-time Stage'],
  ['分期', 'Stage'],
  ['控制分期', 'Control Stage'],
  ['模型睡眠概率', 'Model Sleep Probability'],
  ['保守概率 / 阈值', 'Conservative Probability / Threshold'],
  ['覆盖率', 'Coverage'],
  ['最大缺口', 'Maximum Gap'],
  ['推理耗时', 'Inference Time'],
  ['上下文', 'Context'],
  ['上下文未满，自动停止保持门控', 'Context incomplete; automatic stop remains gated'],
  ['240 秒上下文就绪，允许自动控制', '240 s context ready; automatic control allowed'],
  ['候选动作', 'Candidate Action'],
  ['实际动作', 'Applied Action'],
  ['服务：', 'Service: '],
  ['会话：', 'Session: '],
  ['音乐引导已关闭', 'Music Guidance Disabled'],
  ['等待选择音乐', 'Waiting for Music Selection'],
  ['人工控制中', 'Manual Control'],
  ['等待 30 秒有效分期', 'Waiting for 30 s of valid staging'],
  ['正在建立个体 Alpha 基线', 'Establishing individual Alpha baseline'],
  ['自动开始播放', 'Start Playback Automatically'],
  ['淡出并停止', 'Fade Out and Stop'],
  ['保持上一状态', 'Hold Previous State'],
  ['等待自动触发', 'Waiting for Automatic Trigger'],
  ['等待点击开始助眠', 'Click Start Sleep Guidance'],
  ['等待进入放松', 'Waiting for Relaxation'],
  ['脑电状态持续分析中', 'Continuous EEG analysis'],
  ['放松已确认', 'Relaxation Confirmed'],
  ['Alpha 活动达到播放条件', 'Alpha activity reached the playback criterion'],
  ['正在进入浅睡', 'Entering Light Sleep'],
  ['困意上升，音乐音量同步渐弱', 'Drowsiness increasing; music fades accordingly'],
  ['浅睡已确认', 'Light Sleep Confirmed'],
  ['音乐正在淡出并停止', 'Music is fading out and stopping'],
  ['自动控制已保持上一状态', 'Automatic control is holding the previous state'],
  ['开始助眠', 'Start Sleep Guidance'],
  ['结束助眠', 'End Sleep Guidance'],
  ['助眠已结束', 'Sleep guidance ended'],
  ['打开助眠音乐库', 'Open Sleep Music Library'],
  ['音乐库', 'Music Library'],
  ['重置睡眠演示', 'Reset Sleep Demo'],
  ['开始新的睡眠演示', 'Start a New Sleep Demo'],
  ['尚未选择音乐', 'No Music Selected'],
  ['请选择本地音乐', 'Select Local Music'],
  ['阶段进度', 'Stage Progress'],
  ['当前 Alpha 相对个体睁眼基线', 'Current Alpha relative to the individual eyes-open baseline'],
  ['音乐开启阈值', 'Music Trigger Threshold'],
  ['PC 分期算法保守睡眠概率', 'Conservative sleep probability from PC staging'],
  ['困意', 'Drowsiness'],
  ['质量', 'Quality'],
  ['添加音乐', 'Add Music'],
  ['移除曲目', 'Remove Track'],
  ['上一首', 'Previous'],
  ['下一首', 'Next'],
  ['正在播放', 'Now Playing'],
  ['暂停音乐', 'Pause Music'],
  ['播放音乐', 'Play Music'],
  ['音乐播放进度', 'Music Progress'],
  ['音乐音量', 'Music Volume'],
  ['自动控制', 'Automatic Control'],
  ['三次眨眼降低 10%，五次眨眼提高 10%', 'Three blinks lower volume by 10%; five blinks raise it by 10%'],
  ['眨眼', 'Blink'],
  ['Alpha 与眨眼配对算法遥测', 'Alpha and Paired-blink Algorithm Telemetry'],
  ['Alpha 与眨眼配对遥测', 'Alpha and Paired-blink Telemetry'],
  ['睁眼基线测量进度', 'Eyes-open Baseline Calibration Progress'],
  ['闭眼基线测量进度', 'Eyes-closed Baseline Calibration Progress'],
  ['眨眼基线测量进度', 'Blink Baseline Calibration Progress'],
  ['睁眼基线', 'Eyes-open Baseline'],
  ['闭眼基线', 'Eyes-closed Baseline'],
  ['眨眼基线', 'Blink Baseline'],
  ['眨眼配对', 'Blink Pairing'],
  ['Alpha 水平', 'Alpha Level'],
  ['Alpha 占比 / 开启阈值', 'Alpha Share / Trigger Threshold'],
  ['睁眼基线变化', 'Eyes-open Baseline Change'],
  ['推荐音量', 'Recommended Volume'],
  ['目标音量', 'Target Volume'],
  ['启用配对', 'Enabled Pairs'],
  ['配对有效峰', 'Valid Paired Peaks'],
  ['配对一致率', 'Pair Consensus'],
  ['待确认眨眼', 'Pending Blinks'],
  ['待确认计数', 'Pending Count'],
  ['单通道拒绝', 'Single-channel Rejections'],
  ['缺包拒绝', 'Gap Rejections'],
  ['丢包拒绝 / 补偿', 'Gap Rejections / Recoveries'],
  ['丢包拒绝', 'Gap Rejections'],
  ['节律补偿', 'Rhythm Recoveries'],
  ['模板拒绝', 'Template Rejections'],
  ['异常峰组', 'Abnormal Peak Groups'],
  ['组级命令', 'Group Commands'],
  ['健康检查', 'Health Checks'],
  ['基线健康检查', 'Baseline Health Checks'],
  ['漂移重标', 'Drift Recalibrations'],
  ['自动恢复 / 暂停配对', 'Auto Recovery / Paused Pairs'],
  ['自动恢复', 'Auto Recovery'],
  ['暂停配对', 'Paused Pairs'],
  ['当前强度', 'Current Strength'],
  ['当前宽度', 'Current Width'],
  ['触发阈值', 'Trigger Threshold'],
  ['复位阈值', 'Rearm Threshold'],
  ['模板相关', 'Template Correlation'],
  ['有效配对', 'Enabled Pairs'],
  ['隔离配对', 'Disabled Pairs'],
  ['连续眨眼中冻结在线基线', 'Online baseline frozen during blink sequence'],
  ['组间自适应基线', 'Adaptive inter-group baseline'],
  ['恢复进度', 'Recovery Progress'],
  ['基线漂移：控制暂停并快速恢复中', 'Baseline drift: control paused and fast recovery active'],
  ['眨眼模板与基线健康，控制就绪', 'Blink template and baseline healthy; control ready'],
  ['等待眨眼校准与稳定检查', 'Waiting for blink calibration and stability check'],
  ['漂移恢复中', 'Drift Recovery'],
  ['基线漂移恢复中', 'Baseline Drift Recovery'],
  ['恢复后自动重开控制', 'control resumes automatically after recovery'],
  ['前 3 秒保持静止', 'Remain still for the first 3 s'],
  ['连续自然眨眼', 'Blink naturally and continuously'],
  ['先静止 3 秒', 'Remain still for 3 s first'],
  ['次待确认', 'pending'],
  ['测量失败', 'Calibration Failed'],
  ['待测量', 'Not Calibrated'],
  ['开始 3+10 秒眨眼测量', 'Start 3+10 s Blink Calibration'],
  ['重新测量眨眼基线', 'Recalibrate Blink Baseline'],
  ['测量 3+10 秒', 'Calibrate 3+10 s'],
  ['开始测量', 'Start Calibration'],
  ['重新测量', 'Recalibrate'],
  ['测量完成', 'Calibration Complete'],
  ['测量进度', 'Calibration Progress'],
  ['参考强度', 'Reference Strength'],
  ['参考阈值', 'Reference Threshold'],
  ['参考 ', 'Reference '],
  ['校准峰', 'Calibration Peaks'],
  ['一致率', 'Consensus'],
  ['稳定等待', 'Stabilization Wait'],
  ['校准失败', 'Calibration Failed'],
  ['同步峰、一致率或强度不足', 'Insufficient synchronized peaks, consensus or strength'],
  ['就绪', 'Ready'],
  ['未就绪', 'Not Ready'],
  ['本地', 'Local'],
  ['配对', 'Pairing'],
  ['未启用', 'Disabled'],
  ['本地降级', 'Local Fallback'],
  ['连接中', 'Connecting'],
  ['PC 睡眠算法', 'PC Sleep Algorithm'],
  ['PC v1.2 实时算法', 'PC v1.2 Real-time Algorithm'],
  ['算法连接中', 'Connecting Algorithm'],
  ['算法预热', 'Algorithm Warm-up'],
  ['本地实时判定', 'Local Real-time Detection'],
  ['本地 Alpha / 眨眼检测', 'Local Alpha / Blink Detection'],
  ['算法环境就绪', 'Algorithm Environment Ready'],
  ['算法环境未安装', 'Algorithm Environment Not Installed'],
  ['算法环境尚未安装', 'Algorithm environment is not installed'],
  ['运行中', 'Running'],
  ['未运行', 'Not Running'],
  ['启用 PC v1.2 算法', 'Enable PC v1.2 Algorithm'],
  ['服务地址', 'Service Address'],
  ['算法目录', 'Algorithm Directory'],
  ['停止服务', 'Stop Service'],
  ['启动服务', 'Start Service'],
  ['启动本地睡眠算法服务', 'Start Local Sleep Algorithm Service'],
  ['启用音乐引导', 'Enable Music Guidance'],
  ['自动音乐：检测 Alpha 后播放', 'Automatic Music: Play after Alpha Detection'],
  ['自动音乐：Alpha 后播放', 'Automatic Music: Play after Alpha'],
  ['Alpha 强度调节音量', 'Alpha-controlled Volume'],
  ['在线检测入睡后关闭音乐', 'Stop Music after Online Sleep Detection'],
  ['入睡后关闭音乐', 'Stop Music after Sleep Onset'],
  ['大屏动作提示', 'Large Action Notification'],
  ['助眠歌单', 'Sleep Playlist'],
  ['尚未添加音乐', 'No Music Added'],
  ['音频播放设备', 'Audio Output Device'],
  ['系统默认输出', 'System Default Output'],
  ['授权刷新', 'Authorize & Refresh'],
  ['测试声音', 'Test Sound'],
  ['测试输出声音', 'Test Output Sound'],
  ['刷新音频设备', 'Refresh Audio Devices'],
  ['播放音量', 'Playback Volume'],
  ['最高音量阈值', 'Maximum Volume'],
  ['渐弱目标', 'Fade Target'],
  ['停止淡出', 'Stop Fade Duration'],
  ['演示阶段', 'Demo Stage'],
  ['跟随实时数据', 'Follow Live Data'],
  ['等待放松', 'Waiting for Relaxation'],
  ['放松并播放', 'Relax and Play'],
  ['入睡并渐弱', 'Sleep Onset and Fade'],
  ['浅睡并停止', 'Light Sleep and Stop'],
  ['眨眼音量控制', 'Blink Volume Control'],
  ['眨眼调节音量', 'Blink-controlled Volume'],
  ['眨眼调节步长', 'Blink Volume Step'],
  ['Alpha 音量模式', 'Alpha Volume Mode'],
  ['当前音量', 'Current Volume'],
  ['3 阶梯', '3 Steps'],
  ['10 阶梯', '10 Steps'],
  ['20 阶梯', '20 Steps'],
  ['3 级平滑', '3-step Smoothing'],
  ['10 级精细', '10-step Fine'],
  ['20 级精细', '20-step Fine'],
  ['连续平滑', 'Continuous Smoothing'],
  ['平滑', 'Smooth'],
  ['本地降级 Alpha 阈值', 'Local-fallback Alpha Threshold'],
  ['困意渐弱阈值', 'Drowsiness Fade Threshold'],
  ['困意停止阈值', 'Drowsiness Stop Threshold'],
  ['最低信号覆盖率', 'Minimum Signal Coverage'],
  ['放松确认 s', 'Relax Confirmation s'],
  ['渐弱确认 s', 'Fade Confirmation s'],
  ['浅睡确认 s', 'Light-sleep Confirmation s'],
  ['清醒恢复 s', 'Awake Recovery s'],
  ['平滑系数 EMA', 'EMA Smoothing'],
  ['助眠音乐库', 'Sleep Music Library'],
  ['脑波音频', 'Brainwave Audio'],
  ['自然声景', 'Nature Soundscapes'],
  ['白噪音', 'White Noise'],
  ['冥想', 'Meditation'],
  ['本地音乐', 'Local Music'],
  ['全部声音', 'All Sounds'],
  ['最近播放', 'Recently Played'],
  ['全部', 'All'],
  ['最近', 'Recent'],
  ['搜索声音或文件', 'Search sounds or files'],
  ['搜索助眠音乐', 'Search Sleep Music'],
  ['导入本地音乐', 'Import Local Music'],
  ['导入中', 'Importing'],
  ['关闭音乐库', 'Close Music Library'],
  ['关闭', 'Close'],
  ['音乐分类', 'Music Categories'],
  ['个结果', 'results'],
  ['点击播放按钮授权试听', 'Click Play to authorize preview'],
  ['加入歌单并选择', 'Add to Playlist and Select'],
  ['选择', 'Select'],
  ['试听中', 'Previewing'],
  ['即将试听', 'Preview Starting'],
  ['停止试听', 'Stop Preview'],
  ['试听', 'Preview'],
  ['移出助眠歌单', 'Remove from Sleep Playlist'],
  ['加入助眠歌单', 'Add to Sleep Playlist'],
  ['移出歌单', 'Remove from Playlist'],
  ['加入歌单', 'Add to Playlist'],
  ['从音乐库卡片移出', 'Remove from Library Card'],
  ['从音乐库移除', 'Remove from Music Library'],
  ['没有匹配的声音', 'No Matching Sounds'],
  ['首本地音频', 'local audio files'],
  ['个声音', 'sounds'],
  ['首歌单', 'playlist tracks'],
  ['上移', 'Move Up'],
  ['下移', 'Move Down'],
  ['从播放队列移出', 'Remove from Queue'],
  ['歌单为空', 'Playlist is Empty'],
  ['等待选择', 'Waiting for Selection'],
  ['主题', 'Theme'],
  ['全屏', 'Fullscreen'],
  ['退出全屏', 'Exit Fullscreen'],
  ['进入全屏', 'Enter Fullscreen'],
  ['设置', 'Settings'],
  ['常规', 'General'],
  ['信号', 'Signal'],
  ['助眠', 'Sleep'],
  ['设备', 'Device'],
  ['自动重连', 'Automatic Reconnect'],
  ['预热秒数', 'Warm-up Seconds'],
  ['预热', 'Warm-up'],
  ['保存目录', 'Save Directory'],
  ['留空使用默认目录', 'Leave blank to use the default directory'],
  ['选择目录', 'Choose Directory'],
  ['收起数据面板', 'Collapse Data Panel'],
  ['展开数据面板', 'Expand Data Panel'],
  ['数据面板', 'Data Panel'],
  ['退出', 'Exit'],
  ['低质量', 'Low Quality'],
  ['等待数据', 'Waiting for Data'],
  ['等待信号', 'Waiting for Signal'],
  ['等待', 'Waiting'],
  ['已完成', 'Complete'],
  ['通过', 'Passed'],
  ['未通过', 'Failed'],
  ['尚未检出命令', 'No command detected yet'],
  ['检出', 'Detected '],
  ['预期', 'Expected'],
  ['秒', 's'],
  ['次', ' times'],
  ['当前', 'Current'],
  ['初始', 'Initial'],
  ['变化', 'Change'],
  ['更新', 'Updates'],
  ['会话内冻结', 'Frozen during session'],
  ['缓慢自适应', 'Slow adaptation'],
  ['参考强度', 'Reference Strength'],
  ['暂停', 'Pause'],
  ['播放', 'Play'],
  ['电量', 'Battery'],
  ['记录', 'Record'],
  ['待机', 'Standby']
];

const SORTED_PHRASES = [...ENGLISH_PHRASES].sort((left, right) => right[0].length - left[0].length);
const TRANSLATABLE_ATTRIBUTES = ['aria-label', 'aria-description', 'title', 'placeholder'];

export function translateEnglishUiText(input: string): string {
  if (!containsHan(input)) return input;
  let output = input;
  for (const [source, translation] of SORTED_PHRASES) {
    if (output.includes(source)) output = output.split(source).join(translation);
  }
  return output
    .split('，').join(', ')
    .split('；').join('; ')
    .split('：').join(': ')
    .split('（').join(' (')
    .split('）').join(')')
    .split('。').join('.')
    .replace(/ {2,}/g, ' ');
}

export function installEnglishUi(root: ParentNode = document): () => void {
  document.documentElement.lang = 'en';
  document.title = 'iFET EEG Client Sleep EN 0.2.26';
  translateSubtree(root);
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === 'characterData') {
        translateTextNode(mutation.target);
      } else if (mutation.type === 'attributes' && mutation.target instanceof Element) {
        translateAttributes(mutation.target);
      } else {
        mutation.addedNodes.forEach((node) => translateSubtree(node));
      }
    }
  });
  observer.observe(root, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: TRANSLATABLE_ATTRIBUTES
  });
  return () => observer.disconnect();
}

function translateSubtree(root: Node | ParentNode): void {
  if (root instanceof Text) translateTextNode(root);
  if (root instanceof Element) translateAttributes(root);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateTextNode(node);
    node = walker.nextNode();
  }
  if ('querySelectorAll' in root) {
    (root as ParentNode).querySelectorAll('*').forEach(translateAttributes);
  }
}

function translateTextNode(node: Node): void {
  const source = node.nodeValue ?? '';
  const translated = translateEnglishUiText(source);
  if (translated !== source) node.nodeValue = translated;
}

function translateAttributes(element: Element): void {
  for (const name of TRANSLATABLE_ATTRIBUTES) {
    const source = element.getAttribute(name);
    if (!source) continue;
    const translated = translateEnglishUiText(source);
    if (translated !== source) element.setAttribute(name, translated);
  }
}

function containsHan(value: string): boolean {
  return /\p{Script=Han}/u.test(value);
}
